[project]
name = "sewage"
r_version = "4.6"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
  { alias = "CRAN", url = "https://packagemanager.posit.co/cran/2026-05-12" },
]

# A list of packages to install and any additional configuration
# Examples:
# "dplyr",
# {name = "dplyr", repository = "CRAN"},
# {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
  "DBI",
  "DIDmultiplegtDYN",
  "Deriv",
  "DescTools",
  "DiagrammeR",
  "Exact",
  "Formula",
  "KernSmooth",
  "MASS",
  "Matrix",
  "MatrixModels",
  "PostcodesioR",
  "R.methodsS3",
  "R.oo",
  "R.utils",
  "R6",
  "RColorBrewer",
  "Rcpp",
  "RcppArmadillo",
  "RcppEigen",
  "Rdpack",
  "S7",
  "SparseM",
  "TTR",
  "V8",
  "abind",
  "adagio",
  "arrow",
  "askpass",
  "assertthat",
  "backports",
  "base64enc",
  "bayestestR",
  "bdsmatrix",
  "bigD",
  "biglm",
  "bit",
  "bit64",
  "bitops",
  "blob",
  "boot",
  "broom",
  "bslib",
  "cachem",
  "callr",
  "car",
  "carData",
  "cellranger",
  "checkmate",
  "class",
  "classInt",
  "cli",
  "clipr",
  "codetools",
  "collapse",
  "colorspace",
  "colourpicker",
  "commonmark",
  "conflicted",
  "cowplot",
  "cpp11",
  "crayon",
  "crosstalk",
  "curl",
  "data.table",
  "datawizard",
  "dbplyr",
  "digest",
  "doBy",
  "doParallel",
  "dplyr",
  "dreamerr",
  "dtplyr",
  "duckdb",
  "e1071",
  "evaluate",
  "exactextractr",
  "expm",
  "farver",
  "fastLink",
  "fastmap",
  "fixest",
  "fontawesome",
  "forcats",
  "foreach",
  "forecast",
  "foreign",
  "fracdiff",
  "fs",
  "furrr",
  "future",
  "gargle",
  "generics",
  "ggExtra",
  "ggfixest",
  "ggmap",
  "ggplot2",
  "gld",
  "globals",
  "glue",
  "googledrive",
  "googlesheets4",
  "gridExtra",
  "gt",
  "gtable",
  "gtools",
  "haven",
  "here",
  "highr",
  "hms",
  "htmltools",
  "htmlwidgets",
  "httpuv",
  "httr",
  "ids",
  "igraph",
  "insight",
  "isoband",
  "iterators",
  "janitor",
  "jpeg",
  "jquerylib",
  "jsonlite",
  "juicyjuice",
  "knitr",
  "labeling",
  "later",
  "lattice",
  "lazyeval",
  "leaflet",
  "leaflet.providers",
  "legendry",
  "lifecycle",
  "listenv",
  "litedown",
  "lme4",
  "lmom",
  "lmtest",
  "logger",
  "lpSolve",
  "lubridate",
  "magrittr",
  "marginaleffects",
  "markdown",
  "matlib",
  "matrixStats",
  "maxLik",
  "memoise",
  "memuse",
  "mgcv",
  "microbenchmark",
  "mime",
  "miniUI",
  "minqa",
  "miscTools",
  "modelr",
  "modelsummary",
  "mvtnorm",
  "ncdf4",
  "nlme",
  "nloptr",
  "nnet",
  "numDeriv",
  "openssl",
  "openxlsx",
  "otel",
  "pacman",
  "parallelly",
  "parameters",
  "pbapply",
  "pbkrtest",
  "performance",
  "pillar",
  "pkgconfig",
  "plm",
  "plotly",
  "plotrix",
  "plyr",
  "png",
  "prettyunits",
  "processx",
  "progress",
  "promises",
  "proxy",
  "ps",
  "purrr",
  "quadprog",
  "quantmod",
  "quantreg",
  "ragg",
  "ranger",
  "rappdirs",
  "raster",
  "rbibutils",
  "reactR",
  "reactable",
  "readr",
  "readxl",
  "reclin2",
  "reformulas",
  "rematch",
  "rematch2",
  "remotes",
  "reprex",
  "rgl",
  "rio",
  "rlang",
  "rmarkdown",
  "rnames",
  "rnaturalearth",
  "rnaturalearthdata",
  "rnrfa",
  "rootSolve",
  "rprojroot",
  "rstudioapi",
  "rvest",
  "s2",
  "sandwich",
  "sass",
  "scales",
  "selectr",
  "sf",
  "sfarrow",
  "shiny",
  "shinyjs",
  "showtext",
  "showtextdb",
  "snakecase",
  "sourcetools",
  "sp",
  "speedglm",
  "stringdist",
  "stringi",
  "stringmagic",
  "stringr",
  "survival",
  "sys",
  "sysfonts",
  "systemfonts",
  "tables",
  "terra",
  "textshaping",
  "tibble",
  "tidyr",
  "tidyselect",
  "tidyverse",
  "timeDate",
  "timechange",
  "tinytable",
  "tinytex",
  "tseries",
  "tzdb",
  "units",
  "urca",
  "utf8",
  "uuid",
  "vctrs",
  "viridis",
  "viridisLite",
  "visNetwork",
  "vroom",
  "withr",
  "wk",
  "writexl",
  "xfun",
  "xml2",
  "xtable",
  "xts",
  "yaml",
  "zip",
  "zoo",
  { name = "readxlsb", git = "https://github.com/velofrog/readxlsb", commit = "644ef7aefd4b1342d6754db7bab3dc9310137da7" },
    "nanoparquet",
    "ggmapinset",
    "pdftools",
]
