source(here::here("docs", "reports", "2026-09-03-003-heterogeneity-by-salience-report", "restore_legacy_data.R"))
source(here::here("scripts", "R", "utils", "open_coast_contracts.R"))
root <- tempfile("salience-recovery-")
archive <- file.path(root, "archive")
live <- file.path(root, "live")
dir.create(archive, recursive = TRUE)
dir.create(live)
old_sites <- tibble::tibble(site_id = 1:2, distance_to_coast_m = c(1, 3000),
  bath_ever_2124 = c(TRUE, FALSE), bath_unknown_2124 = FALSE)
old_radius <- tibble::tibble(house_id = c("one", "two"), radius = 250L,
  min_coast_dist_m = c(1, 3000), any_bath_2124 = c(TRUE, FALSE), bath_unknown_2124 = FALSE)
arrow::write_parquet(old_sites, file.path(archive, "site.parquet"))
arrow::write_parquet(old_radius, file.path(archive, "radius.parquet"))
entries <- lapply(c("site.parquet", "radius.parquet"), function(path)
  list(path = path, sha256 = salience_file_hash(file.path(archive, path))))
manifest <- list(profile = "legacy_tidal", recovery_root = archive, recovery = entries)
manifest_path <- file.path(root, "manifest.json")
jsonlite::write_json(manifest, manifest_path, auto_unbox = TRUE)
# Simulate site promotion followed by an interrupted companion build after the
# actual five consumers have switched to the refined profile.
generation <- paste(rep("a", 64), collapse = "")
new_sites <- dplyr::mutate(old_sites, distance_to_open_coast_m = c(4000, 5000),
  open_coast_status = "validated", geometry_generation = generation, site_generation = generation)
arrow::write_parquet(new_sites, file.path(live, "site.parquet"))
arrow::write_parquet(old_radius, file.path(live, "radius.parquet"))
expect_error <- function(expr) stopifnot(inherits(tryCatch(force(expr), error = identity), "error"))
expect_error(validate_open_coast_radius(arrow::read_parquet(file.path(live, "radius.parquet")), generation))
restore_legacy_data(manifest_path, live)
stopifnot(all(vapply(entries, function(x) identical(salience_file_hash(file.path(live, x$path)), x$sha256), logical(1))))
expect_error(validate_open_coast_sites(arrow::read_parquet(file.path(live, "site.parquet"))))
# Matching historical code restores the original classification; it is never an
# implicit fallback inside a refined consumer.
legacy <- new.env(parent = globalenv())
snapshot <- file.path(salience_report_root(), "historical", "source", "scripts", "R", "utils", "salience_group_utils.R")
if (!file.exists(snapshot)) stop("Preserved legacy consumer source is required for recovery verification.")
sys.source(snapshot, legacy)
classified <- legacy$classify_salience_groups(dplyr::mutate(arrow::read_parquet(file.path(live, "site.parquet")), region = NA_character_))
stopifnot(identical(classified$coastal, c(TRUE, FALSE)), identical(classified$inland, c(FALSE, TRUE)))
unlink(root, recursive = TRUE)
cat("Interrupted-generation recovery and explicit legacy-consumer contracts passed.\n")
