project:
  type: book
  output-dir: _site

book:
  title: "Sewage in Our Waters"
  author: "Jacopo Olivieri"
  date: "last-modified"
  chapters:
    - index.qmd
    - part: "Data Exploration"
      chapters:
      - data_limitations.qmd
      - spill_data_exploration.qmd
      - dry_spills.qmd
      - house_data_exploration.qmd
      - zoopla_data_exploration.qmd
    - part: "Analysis"
      chapters:
      - event_study.qmd
      - hedonic_regs.qmd
    - part: "Data Cleaning"
      chapters: 
      - data_clean_documentation/01_pipeline.qmd
      - data_clean_documentation/02_ingestion.qmd

bibliography: refs.bib

format:
  html:
    theme: lux
    embed-resources: false
    css: styles.css

editor: source
