project:
  type: book
  output-dir: _site

book:
  title: "Sewage in Our Waters"
  author: "Jacopo Olivieri"
  date: "last-modified"
  chapters:
    - index.qmd
    - data_limitations.qmd
    - spill_data_exploration.qmd
    - house_data_exploration.qmd
    - event_study.qmd
    - hedonic_regs.qmd

bibliography: refs.bib

format:
  html:
    theme: lux
    embed-resources: false
    css: styles.css

editor: source

