---
author: "Jacopo Olivieri"
date: 2024-12-22
editor: source
number-sections: true
number-depth: 4
execute: 
  echo: false
  warning: false
  message: false
  freeze: false
  fig-width: 6
  fig-asp: 0.618 
  fig-align: center
---

# Updates {#sec-index}

## 29/08/2025 {.unnumbered}

Added MSOA-level aggregation, population-adjusted metrics, and multi-perspective choropleth visualizations to sewage spill geographic analysis (Geographic Distribution, @sec-03-03-geo-distribution).

## 03/06/2025 {.unnumbered}

Added section on hedonic regression analysis of house prices (Hedonic Regression Analysis, @sec-06-hedonics-regs).

## 01/04/2025 {.unnumbered}

Added section on event study analysis of sewage spills (Event Study Analysis, @sec-05-event-study).

## 18/02/2025 {.unnumbered}

Added section on initial data exploration of house prices and sewage spills (House Data Exploration @sec-04-house-exploration).

## 17/02/2025 {.unnumbered}

Updated sewage overflow spills section with additional descriptive statistics (Sewage Spill Data Exploration, @sec-03-spill-exploration).

## 02/01/2025 {.unnumbered}

Added section on initial data exploration of sewage overflow spills (Sewage Spill Data Exploration, @sec-03-spill-exploration).

## 30/12/2024 {.unnumbered}

Added section on incorrect spill data duration (Current Data Limitations, @sec-02-02-time-parsing).

## 24/12/2024 {.unnumbered}

Added section on the merge of location data to inidividual spill data (Current Data Limitations,  @sec-02-limitations).

## 22/12/2024 {.unnumbered}

Start of Sewage in Our Waters website!